phrase:
  access_token: b7fc60cd08e349735c546d147186900a91ec509bf763e515ea531affb3cd4c29
  project_id: dd47f37ec9ef96822eb0ebc163ebf349
  push:
    sources:
    - file: ./i18n/l10n/en/translation.json
      params:
        locale_id: en
        file_format: simple_json
  pull:
    targets:
    - file: ./i18n/l10n/<locale_name>/translation.json
      params:
        file_format: simple_json
